# Generated by Django 3.2 on 2023-06-12 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuserprofile',
            name='bio',
            field=models.TextField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='customuserprofile',
            name='occupation',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
    ]
