# Generated by Django 3.2 on 2023-06-13 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
        ('accounts', '0005_alter_customuserprofile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuserprofile',
            name='city',
            field=models.ForeignKey(blank=True, help_text='Select a city', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_light.city'),
        ),
        migrations.AlterField(
            model_name='customuserprofile',
            name='country',
            field=models.ForeignKey(blank=True, help_text='Select a country', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_light.country'),
        ),
        migrations.AlterField(
            model_name='customuserprofile',
            name='region',
            field=models.ForeignKey(blank=True, help_text='Select a region', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_light.region'),
        ),
    ]
